name: Build & release mod on GitHub

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        default: '0.0.0'


jobs:
  release:
    name: Build & release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Build mod
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon

      - name: Release mod
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version_tag }}
          files: |
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
